def loomLocalRepo = System.getenv('LOOM_M2') ?: new File(settingsDir, 'local-plugins').absolutePath

pluginManagement {
    repositories {
        if (file(loomLocalRepo).exists()) {
            maven {
                name = "LoomLocal"
                url = uri(loomLocalRepo)
            }
        }
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "fabric-loom") {
                useModule("net.fabricmc:fabric-loom:${requested.version}")
            }
        }
    }
}

rootProject.name = 'Finicalfirecooldown'
